### ISSUE TITLE
Support for New Relic integrations

### ISSUE THREAD

**Issue by rcmachado** [xo/dburl#14]
New Relic database integrations rely on custom drivers (eg. `nrpostgres`, `nrmysql`, etc) to monitor database queries.

Since the list of drivers is predefined in `scheme.go`, supporting New Relic drivers require a manual overwrite after the URL is parsed.

I was thinking in opening a PR adding [New Relic drivers](https://github.com/newrelic/go-agent) as aliases for each supported driver, but I'm not sure if that's under the scope of the project. Another option could be use the [`sql.Drivers()`](https://pkg.go.dev/database/sql) to retrieve a list of registered drivers - but I'm not sure if we could get all the information from there.

Any thoughts on that?

**Comment by kenshaw** [comment]
@rcmachado -- as a general purpose extension to `dburl` probably not, since New Relic itself isn't a database. Please note, that there's already an API in `dburl` that [can allow you to register aliases for these additional schemes](https://godoc.org/github.com/xo/dburl#RegisterAlias). The way it would be used would be in an `init` func:

```go
func init() {
    dburl.RegisterAlias("postgres", "nrpostgres")
}
```
Any package then looking to import or use your code would then be able to use `dburl.Parse` and `dburl.Open` with URLs of the form `nrpostgres://`. `dburl` in turn would generate DSNs for use with Go's standard SQL packages for any URL beginning with the `nrpostgres://` scheme. If you'd like to register a custom URL scheme with `dburl`, that generates its DSNs differently, please see the `dburl.Scheme` type, and the `dburl.Register` func.

**Comment by rcmachado** [comment]
@kenshaw That's great - missed the `RegisterAlias` function, sorry. I'll close this for now (as it's just a wrapper around a real driver, the alias will work).

Thanks!
