### ISSUE TITLE
TestParse failure

### ISSUE THREAD

**Issue by dolmen** [xo/dburl#6]
```
$ git describe --always --dirty
cd61869
$ go test
--- FAIL: TestParse (0.00s)
	dburl_test.go:157: test 3 expected DSN `host=/var/run/postgresql`, got: `dbname=postgresql host=/var/run`
	dburl_test.go:157: test 4 expected DSN `dbname=mydb host=/var/run/postgresql port=6666`, got: `dbname=postgresql:6666/mydb host=/var/run`
	dburl_test.go:157: test 5 expected DSN `dbname=mydb host=/var/run/postgresql`, got: `dbname=postgresql/mydb host=/var/run`
	dburl_test.go:157: test 6 expected DSN `host=/var/run/postgresql port=7777`, got: `dbname=postgresql:7777 host=/var/run`
	dburl_test.go:157: test 7 expected DSN `dbname=booktest host=/var/run/postgresql port=4444`, got: `dbname=postgresql:4444/booktest host=/var/run`
	dburl_test.go:157: test 8 expected DSN `dbname=mydb host=/var/run/postgresql password=pass user=user`, got: `dbname=postgresql/mydb host=/var/run password=pass user=user`
	dburl_test.go:157: test 13 expected DSN `unix(/var/run/mysqld/mysqld.sock)/mydb?timeout=90`, got: `unix(/var/run/mysqld/mysqld.sock/mydb)/?timeout=90`
	dburl_test.go:157: test 14 expected DSN `unix(/var/run/mysqld/mysqld.sock)/mydb?timeout=90`, got: `unix(/var/run/mysqld/mysqld.sock/mydb)/?timeout=90`
	dburl_test.go:157: test 21 expected DSN `unix:/var/run/mysqld/mysqld.sock,test,timeout=90*mydb`, got: `unix:/var/run/mysqld/mysqld.sock/mydb,test,timeout=90*//`
	dburl_test.go:157: test 22 expected DSN `unix:/var/run/mysqld/mysqld.sock,timeout=90*mydb`, got: `unix:/var/run/mysqld/mysqld.sock/mydb,timeout=90*//`
FAIL
exit status 1
FAIL	github.com/xo/dburl	0.008s
```

This package only imports package from stdlib (according to `go list -json`), so this doesn't seem to be a version dependency issue.

This result is inconsistent with the [build success on Travis](https://travis-ci.org/xo/dburl/builds/392983287), so I don't understand what's happening.

**Comment by kenshaw** [comment]
I cannot reproduce this. I would need more information. Did you modify/change your local copy of the repository?

**Comment by dolmen** [comment]
No, I have not changed my local copy. `go describe --always --dirty` would have reported this (`--dirty` flag).

**Comment by kenshaw** [comment]
@dolmen I would need more information then. Are you running an old version of Go or some such? Please provide information on the platform / go version / etc. you're using. Otherwise, I have nothing available to me to reproduce this behavior.

**Comment by dolmen** [comment]
```
go version go1.10.3 darwin/amd64
```

**Comment by dolmen** [comment]
First commit where `go test -run TestParse` fails is c1aceebe8a10cb85e3b7bfe80c4423007f8eda22.

**Comment by dolmen** [comment]
I notice that resolving Postgres URL calls `os.Stat` (in func `mode` in `util.go`).

I don't have Postgres installed on my machine, so `/var/run/postgresql` doesn't exist. This is the difference.

I'm updating the title. Please reopen.

**Comment by dolmen** [comment]
It is very bad that a function called `Parse` has different results depending on the filesystem state.

**Comment by kenshaw** [comment]
@dolmen I appreciate your interest in this project, but this is not an actual issue. The unit tests work properly to test what they were designed to test. If you'd like to submit a PR selectively disabling these unit tests for use on environments where PostgreSQL is not installed, I'd consider merging that.

**Comment by dolmen** [comment]
Because of this issue, the testsuite doesn't work also on non-Unix environments (e.g. Windows).

**Comment by kenshaw** [comment]
@dolmen I've already stated that if you'd like to submit a PR selectively disabling this functionality (ie, for certain environments such as Windows), I'd be open to it. As it is, the reason this won't work on Windows, is because Windows (until very recently) has not supported Unix Domain Sockets. That said, the latest version of Windows 10 1603 [does indeed support Unix Domain Sockets](https://blogs.msdn.microsoft.com/commandline/2017/12/19/af_unix-comes-to-windows/). As such, the *correct* thing to do here would be to:

1) First fix Go to work with `AF_UNIX` on Windows
2) Submit a PR changing the path this is used against, selectively based on OS using Go's build tags

Also, it's worth noting that __unit tests do not need to work on every platform__. These unit tests work for all the testing environments they were designed for. If they are not working on your platform, that's because you're using a non-standard platform (Windows) for development. 

I have no intention of rewriting unit tests to work on broken Windows environments. By and large the users / developers of Go, `usql`, and `dburl` are not using Windows systems. If you would like the unit tests to work on (in my opinion) the broken Windows platform, feel free to submit a PR. I'll gladly accept it assuming it is well written.
